# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

findPath <- function(edge, startx, starty, endx, endy, minX, maxX, minY, maxY, proximity) {
    .Call(`_finFindR_findPath`, edge, startx, starty, endx, endy, minX, maxX, minY, maxY, proximity)
}

initializeImg <- function(imageName, newX, newY) {
    .Call(`_finFindR_initializeImg`, imageName, newX, newY)
}

saveCrop <- function(saveName, xMin, xMax, yMin, yMax, spanX, spanY, thresh) {
    invisible(.Call(`_finFindR_saveCrop`, saveName, xMin, xMax, yMin, yMax, spanX, spanY, thresh))
}

fillGlare <- function(imageFromR, highlightCoordinates, aveThresh = 7L) {
    .Call(`_finFindR_fillGlare`, imageFromR, highlightCoordinates, aveThresh)
}

extractEdgeMap <- function(gradientFromR, anglesFromR) {
    .Call(`_finFindR_extractEdgeMap`, gradientFromR, anglesFromR)
}

extractAngles <- function(angFromR, backpath, startx, starty) {
    .Call(`_finFindR_extractAngles`, angFromR, backpath, startx, starty)
}

